# Generated by Django 3.2.3 on 2023-12-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(default=123, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
