# Generated by Django 3.2.3 on 2023-12-08 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='count',
            new_name='amount',
        ),
    ]
