# Generated by Django 3.2.3 on 2023-12-09 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_best_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='best',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited', to='recipes.recipe'),
        ),
    ]
