# Generated by Django 3.2.3 on 2023-12-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_ingredientrecipe_amount'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='best',
            name='unique_best',
        ),
        migrations.RemoveConstraint(
            model_name='shopcart',
            name='unique_shop_cart',
        ),
        migrations.RenameField(
            model_name='best',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shopcart',
            old_name='author',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='best',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_best'),
        ),
        migrations.AddConstraint(
            model_name='shopcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_shop_cart'),
        ),
    ]
