MAX_NAME_CHARACTERS = 200
MAX_COLOR_CHARACTERS = 16
MAX_SLUG_CHARACTERS = 100
MAX_UNIT_CHARACTERS = 16

MIN_COOKING_VALUE = 1
COOKING_VALIDATION_MESSAGE = 'Введите значение не менее 1 минуты'
MIN_INGREDIENT_VALUE = 1
INGREDIENT_VALIDATION_MESSAGE = 'Выберите не менее одного ингредиента'
